# Generated by Django 5.2.4 on 2025-11-18 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=50, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD')], default='NGN', max_length=20)),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['user_id'], name='id_idx'), models.Index(fields=['email'], name='email_idx'), models.Index(fields=['username'], name='username_idx'), models.Index(fields=['currency'], name='currency_idx')],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(db_index=True, default=uuid.UUID('8f6737c6-2988-4df9-957d-0b18a2e271b7'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Paystack', max_length=250)),
                ('balance', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'db_table': 'accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.UUID('a49d2bec-6654-4808-be9c-451f15a494f5'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], default='EXPENSE', max_length=20)),
                ('is_income', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('Card', 'card'), ('Bank Transfer', 'bank_transfer'), ('USSD', 'ussd'), ('QR Payment', 'qr '), ('BANK', 'bank'), ('MOBILE_MONEY', 'mobile_money')], default='Card', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_of_transaction', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='expense_models.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
