# Generated by Django 5.2.4 on 2025-11-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_models', '0002_alter_customuser_first_name_alter_customuser_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=50),
        ),
    ]
