# Generated by Django 5.2.4 on 2025-11-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_models', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=50, unique=True),
        ),
    ]
