# Generated by Django 5.2.4 on 2025-11-10 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_models', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1598de94-0fa5-42be-be6d-e9b379ad48af'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='NIgerian_Bank', max_length=250)),
                ('account_type', models.CharField(choices=[('BANK', 'Bank'), ('WALLET', 'Wallet')], default='BANK', max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
