# Generated by Django 5.2.4 on 2025-11-10 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_models', '0005_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('220e2819-b13e-4334-9800-1ad357b48fb4'), primary_key=True, serialize=False, unique=True),
        ),
    ]
